const THEMES = {
  embers: {
    "--bg-color": "#41436a",
    "--text-color": "#ff9677",
    "--primary-color": "#f54768",
    "--secondary-color": "#974063",
    "--circle-color": "#ff9677",
    "--circle-alpha": "0.4",
  },
  mystic: {
    "--bg-color": "#4663be",
    "--text-color": "#85f1fe",
    "--primary-color": "#21aee4",
    "--secondary-color": "#8dbafe",
    "--circle-color": "#21aee4",
    "--circle-alpha": "0.5",
  },
  sailor: {
    "--bg-color": "#364c96",
    "--text-color": "#eaebed",
    "--primary-color": "#ff8496",
    "--secondary-color": "#ff8496",
    "--circle-color": "#eaebed",
    "--circle-alpha": "0.6",
  },
  sunset: {
    "--bg-color": "#355c7d",
    "--text-color": "#ff9677",
    "--primary-color": "#ff7582",
    "--secondary-color": "#c56d86",
    "--circle-color": "#ff7582",
    "--circle-alpha": "0.5",
  },
  gotham: {
    "--bg-color": "#243b67",
    "--text-color": "#eaebed",
    "--primary-color": "#c27dfc",
    "--secondary-color": "#6e5dcf",
    "--circle-color": "#c27dfc",
    "--circle-alpha": "0.5",
  },
  sea: {
    "--bg-color": "#006092",
    "--text-color": "#e9ebed",
    "--primary-color": "#82efea",
    "--secondary-color": "#1fc4da",
    "--circle-color": "#9ba5c9",
    "--circle-alpha": "0.4",
  },
  samantha: {
    "--bg-color": "#4a54cf",
    "--text-color": "#e9ebed",
    "--primary-color": "#ffc478",
    "--secondary-color": "#b473d7",
    "--circle-color": "#ffc478",
    "--circle-alpha": "0.4",
  },
  mutable: {
    "--bg-color": "#5778a3",
    "--text-color": "#e3e4e6",
    "--primary-color": "#3bb3b5",
    "--secondary-color": "#6eb4b5",
    "--circle-color": "#3bb3b5",
    "--circle-alpha": "0.4",
  },
  dragon: {
    "--bg-color": "#334f64",
    "--text-color": "#eaebed",
    "--primary-color": "#ffd782",
    "--secondary-color": "#46a8a7",
    "--circle-color": "#46a8a7",
    "--circle-alpha": "0.6",
  },
  lagoon: {
    "--bg-color": "#0295a9",
    "--text-color": "#fff",
    "--primary-color": "#fdd037",
    "--secondary-color": "#12adc1",
    "--circle-color": "#fdd037",
    "--circle-alpha": "0.4",
  },
  moss: {
    "--bg-color": "#016170",
    "--text-color": "#fff",
    "--primary-color": "#00e0c6",
    "--secondary-color": "#009393",
    "--circle-color": "#00e0c6",
    "--circle-alpha": "0.4",
  },
  westly: {
    "--bg-color": "#244d61",
    "--text-color": "#eaebed",
    "--primary-color": "#75e2ff",
    "--secondary-color": "#5689c0",
    "--circle-color": "#75e2ff",
    "--circle-alpha": "0.4",
  },
  sailing: {
    "--bg-color": "#326789",
    "--text-color": "#e9eef2",
    "--primary-color": "#75e2ff",
    "--secondary-color": "#78a6c8",
    "--circle-color": "#e9eef2",
    "--circle-alpha": "0.4",
  },
  lavendar: {
    "--bg-color": "#5e4dab",
    "--text-color": "#e9eef2",
    "--primary-color": "#f582bd",
    "--secondary-color": "#974ec2",
    "--circle-color": "#e9eef2",
    "--circle-alpha": "0.4",
  },
};

const ACTIVE_THEME = "gotham";

export { THEMES, ACTIVE_THEME };